### ISSUE TITLE
Update 47 nullreferenceexception

### ISSUE THREAD

**Issue by skylarkblue1** [EBro912/SpectateEnemies#7] opened 2024-01-09 02:29 UTC
![image](https://github.com/EBro912/SpectateEnemies/assets/15182062/b7880fc4-717f-4a6f-b278-a006e01c3ce8)
Making a new ticket as I believe this to be seperate enough to the other currently open issue as no enemies where dead in this round. Just regular round, enemies where in (coilhead and nutcracker for sure) no enemies dead, 2/4 players dead. Every null reference exception came with the 2D atlus error every time I tried to spectate enemies, both errors where not present for when viewing players.

Seems like the update has made the mod unusable - but at least it's not game breaking.

**Comment by EBro912** [comment] 2024-01-09 02:34
Thanks for reporting, hopefully this'll be fixed once I update the mod to support v47

**Comment by EBro912** [comment] 2024-01-09 21:04
This _may_ be fixed as of the latest release, I was unable to reproduce this bug so try out the newest version and let me know if it helps.

**Comment by skylarkblue1** [comment] 2024-01-13 16:35
It's fixed! Haven't tested the other bug if an enemy is dead but seems like it's at least working now at a base.

**Comment by EBro912** [comment] 2024-01-13 20:22
Great! I'll close this for now, if you run into any more problems please create another issue.

**Closed as completed by EBro912** 2024-01-13 20:22 UTC
