### ISSUE TITLE
[BUG] Spectating an enemy while its killed crashes the game

### ISSUE THREAD

**Issue by VannaERR404** [EBro912/SpectateEnemies#8] opened 2024-01-09 06:40 UTC
See title, was spectating a spider while another player killed it with a shovel and then crashed, wasnt able to recover logs because i closed the game too quickly before thinking about making a bug report

**Comment by EBro912** [comment] 2024-01-09 07:30
Try the latest version on thunderstore if you haven't already

**Comment by VannaERR404** [comment] 2024-01-09 18:00
> Try the latest version on thunderstore if you haven't already

I was using the latest version of the mod, it isnt the only mod im using, i can send you the list of everything if you want

**Comment by EBro912** [comment] 2024-01-09 18:03
Sure, that'd be useful. Were there any other enemies alive when the spider died?

**Comment by VannaERR404** [comment] 2024-01-09 18:11
> Sure, that'd be useful. Were there any other enemies alive when the spider died?

Not certain, it was very early in the day so it wouldnt be strange if it was the only thing.

BepInExPack
MoreCompany
More_Suits
More_Emotes
LateCompany
ShipLoot
AdditionalSuits
AlwaysHearActiveWalkies
HookGenPatcher
LethalLib
LethalThings
SpectateEnemies
BetterStamina
QuickRestart
LethalCompany_InputUtils
BetterEmotes
TerminalApi
Terminal_Clock
Skinwalkers
Mimics
Boombox_Controller
Solos_Bodycams
LC_API
CostlyShotgun
YippeeMod

**Comment by EBro912** [comment] 2024-01-09 18:13
If the spider was the only enemy alive, the mod may have been stuck trying to find another enemy to spectate when there were none, resulting in the crash. I'll try and recreate that scenario and see if I can fix it

**Comment by EBro912** [comment] 2024-01-09 18:16
Actually, looking at the code, I can see why this happens. There should be a value being incremented when it sees a dead enemy which isn't, resulting in an infinite loop. I'll release a hotfix for this later today.

**Comment by VannaERR404** [comment] 2024-01-09 18:22
> If the spider was the only enemy alive, the mod may have been stuck trying to find another enemy to spectate when there were none, resulting in the crash. I'll try and recreate that scenario and see if I can fix it

What I think happened was, taking a brief look at the code, LateUpdate() went into the if check at line 119 and called GetNextValidSpectatable(), and then line 325 tries to find more enemies and assuming there were no more, this would cause errors because FindObjectsByType returns a null if its find nothing and then you try to call a .Where accessing x and x.enemy name when its not even an empty enumerable its null

**Comment by EBro912** [comment] 2024-01-09 18:24
If you run Where on an empty list, it'll just return an empty collection. The problem is inside that check above the continue. enemiesChecked should be incremented here, but it isn't, resulting in the same spider being checked over and over again resulting in the infinite loop.

**Comment by VannaERR404** [comment] 2024-01-09 18:29
> If you run Where on an empty list, it'll just return an empty collection. The problem is inside that check above the continue. enemiesChecked should be incremented here, but it isn't, resulting in the same spider being checked over and over again resulting in the infinite loop.

i believe its not an empty list, its null. I could be wrong. obviously youll know your code better than me tho haha

Dont know how the game works or how to mod it myself but if its possible a suggestion i have is using a static list of enemies, and adding newly spawned enemies to it, and removing those that die/leave, this would let you not even need to do a Find, you could just have the list thats accessible always, and be able to do a .Count() on it to be sure theres more enemies.

**Comment by EBro912** [comment] 2024-01-09 21:04
This should be fixed as of the latest release, closing for now

**Closed as completed by EBro912** 2024-01-09 21:04 UTC
